### ISSUE TITLE
작동하지 않습니다

### ISSUE THREAD

**Issue by polpol7235** [iamjjintta-python/dccon-downloader#1]
항상 잘 쓰고 있습니다. 감사합니다.
최근들어 검색 자체가 안되는 것 같은데 더 이상 운영 안하시는건가요?

**Comment by iam-jjintta** [comment]
@polpol7235 네,, 근래에 들어 프로그래밍에 대한 흥미가 식은 탓에 업데이트를 하고 있지 않아요... ㅠㅅㅠ
혹시라도 다른 분들이 수정해서 커밋 해주시면 반영할게요오오...

**Comment by polpol7235** [comment]
아...ㅠㅠ 알겠습니다 답변감사합니다!!

**Comment by iam-jjintta** [comment]
@polpol7235 미안해요오오오... ㅠㅅㅠ
